name: health_tracker
description: A Flutter application for tracking health symptoms
version: 1.0.0+7  # Incrementar el version_code

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  table_calendar: ^3.0.0
  shared_preferences: ^2.0.0
  uuid: ^3.0.0
  fl_chart: ^0.65.0
  image_picker: ^0.8.0
  path_provider: ^2.0.0
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"

flutter:
  generate: true
  uses-material-design: true 