name: symptom_tracker
description: A Flutter application for tracking health symptoms
version: 1.0.0+1  # Versión inicial

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  table_calendar: ^3.0.0
  shared_preferences: ^2.0.0
  uuid: ^3.0.0
  fl_chart: ^0.60.0
  image_picker: ^0.8.0
  path_provider: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true 