name: symptom_tracker
description: "A symptom tracking application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  table_calendar: ^3.0.9
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  image_picker: ^1.0.7
  path_provider: ^2.1.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true 